/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.14
 * Generated at: 2022-10-24 10:27:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class clientHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/view/footer.jsp", Long.valueOf(1666075742296L));
    _jspx_dependants.put("file:/C:/Users/Серёга/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1652529507264L));
    _jspx_dependants.put("/view/header.jsp", Long.valueOf(1666607248773L));
    _jspx_dependants.put("jar:file:/C:/Users/Серёга/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602863172000L));
    _jspx_dependants.put("/WEB-INF/tag/language.tld", Long.valueOf(1666435784466L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\" crossorigin=\"anonymous\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\" crossorigin=\"anonymous\">\r\n");
      out.write("        <div class=\"card\" >\r\n");
      out.write("            <div class=\"card-header\" >\r\n");
      out.write("                <div class=\"d-grid gap-2 d-md-flex justify-content-md-end\" style = \"display: flex; justify-content: center; align-items: center; height: 100px;\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"card-title\">\r\n");
      out.write("                            <h5>");
      if (_jspx_meth_lang_005fprint_005f0(_jspx_page_context))
        return;
      out.write("</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <form action = \"/app/cargo/logout\" method = \"POST\" >\r\n");
      out.write("                        <input type = \"submit\" class=\"btn btn-primary\" value = '");
      if (_jspx_meth_lang_005fprint_005f8(_jspx_page_context))
        return;
      out.write("'/>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <form action = \"/app/cargo/changeLocale\" method = \"POST\">\r\n");
      out.write("                        <input type = \"submit\" class=\"btn btn-secondary btn-sm\" value = '");
      if (_jspx_meth_lang_005fprint_005f9(_jspx_page_context))
        return;
      out.write("'><br>\r\n");
      out.write("                        <select name = \"selectedLocale\" >\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </head>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <h2>\r\n");
      out.write("            ");
      if (_jspx_meth_lang_005fprint_005f10(_jspx_page_context))
        return;
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.login}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"https://dnepr-more.com/wp-content/uploads/2018/02/gruzoperevozki.jpg\" alt=\"cargo\" style=\"float:left; margin-right:10px;\" />\r\n");
      out.write("            <h1>");
      if (_jspx_meth_lang_005fprint_005f11(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("            <p class=\"lh-lg\" style=\"margin-left: 20px;\">\r\n");
      out.write("                <h5>");
      if (_jspx_meth_lang_005fprint_005f12(_jspx_page_context))
        return;
      out.write("</h5><br>\r\n");
      out.write("                    ");
      if (_jspx_meth_lang_005fprint_005f13(_jspx_page_context))
        return;
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("                    &#34;<u>");
      if (_jspx_meth_lang_005fprint_005f14(_jspx_page_context))
        return;
      out.write("</u>&#34;\r\n");
      out.write("                    - ");
      if (_jspx_meth_lang_005fprint_005f15(_jspx_page_context))
        return;
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("                    &#34;<u>");
      if (_jspx_meth_lang_005fprint_005f16(_jspx_page_context))
        return;
      out.write("</u>&#34;\r\n");
      out.write("                    - ");
      if (_jspx_meth_lang_005fprint_005f17(_jspx_page_context))
        return;
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("                    &#34;<u>");
      if (_jspx_meth_lang_005fprint_005f18(_jspx_page_context))
        return;
      out.write("</u>&#34;\r\n");
      out.write("                    - ");
      if (_jspx_meth_lang_005fprint_005f19(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_lang_005fprint_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f0 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f0_reused = false;
    try {
      _jspx_th_lang_005fprint_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f0.setParent(null);
      // /view/header.jsp(14,32) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f0.setMessage("header.jsp.cargo.application");
      int _jspx_eval_lang_005fprint_005f0 = _jspx_th_lang_005fprint_005f0.doStartTag();
      if (_jspx_th_lang_005fprint_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f0);
      _jspx_th_lang_005fprint_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f0, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /view/header.jsp(18,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'MANAGER'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action =\"/app/manager/managerHome.jsp\" method = \"GET\">\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f1 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f1_reused = false;
    try {
      _jspx_th_lang_005fprint_005f1.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /view/header.jsp(20,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f1.setMessage("header.jsp.home");
      int _jspx_eval_lang_005fprint_005f1 = _jspx_th_lang_005fprint_005f1.doStartTag();
      if (_jspx_th_lang_005fprint_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f1);
      _jspx_th_lang_005fprint_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f1, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /view/header.jsp(24,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'MANAGER'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action = \"/app/cargo/manager/getAllOrders\" method \"GET\">\r\n");
          out.write("                            <input type=\"hidden\" name=\"page\" value=\"1\">\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f2 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f2_reused = false;
    try {
      _jspx_th_lang_005fprint_005f2.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /view/header.jsp(27,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f2.setMessage("header.jsp.get.all.orders");
      int _jspx_eval_lang_005fprint_005f2 = _jspx_th_lang_005fprint_005f2.doStartTag();
      if (_jspx_th_lang_005fprint_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f2);
      _jspx_th_lang_005fprint_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f2, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /view/header.jsp(31,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'MANAGER'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action = \"/app/cargo/manager/getNotConfirmedOrders\" method \"GET\">\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f3 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f3_reused = false;
    try {
      _jspx_th_lang_005fprint_005f3.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /view/header.jsp(33,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f3.setMessage("header.jsp.get.not.confirmed.orders");
      int _jspx_eval_lang_005fprint_005f3 = _jspx_th_lang_005fprint_005f3.doStartTag();
      if (_jspx_th_lang_005fprint_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f3);
      _jspx_th_lang_005fprint_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f3, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /view/header.jsp(37,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'CLIENT'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action =\"/app/cargo/client/routes\" method = \"GET\">\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f4(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f4(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f4 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f4_reused = false;
    try {
      _jspx_th_lang_005fprint_005f4.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f4.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /view/header.jsp(39,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f4.setMessage("header.jsp.place.an.order.for.delivery");
      int _jspx_eval_lang_005fprint_005f4 = _jspx_th_lang_005fprint_005f4.doStartTag();
      if (_jspx_th_lang_005fprint_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f4);
      _jspx_th_lang_005fprint_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f4, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /view/header.jsp(43,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'CLIENT'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action =\"/app/client/clientHome.jsp\" method = \"GET\">\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f5(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f5 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f5_reused = false;
    try {
      _jspx_th_lang_005fprint_005f5.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f5.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /view/header.jsp(45,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f5.setMessage("header.jsp.home");
      int _jspx_eval_lang_005fprint_005f5 = _jspx_th_lang_005fprint_005f5.doStartTag();
      if (_jspx_th_lang_005fprint_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f5);
      _jspx_th_lang_005fprint_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f5, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /view/header.jsp(50,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'CLIENT'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action =\"/app/cargo/client/getWalletInfo\" method = \"GET\">\r\n");
          out.write("                            <input type = \"hidden\" name=\"clientId\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f6(_jspx_th_c_005fif_005f5, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f6(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f6 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f6_reused = false;
    try {
      _jspx_th_lang_005fprint_005f6.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f6.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      // /view/header.jsp(53,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f6.setMessage("header.jsp.my.wallet");
      int _jspx_eval_lang_005fprint_005f6 = _jspx_th_lang_005fprint_005f6.doStartTag();
      if (_jspx_th_lang_005fprint_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f6);
      _jspx_th_lang_005fprint_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f6, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /view/header.jsp(57,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userRole == 'CLIENT'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <form action =\"/app/cargo/client/getClientOrders\" method = \"GET\">\r\n");
          out.write("                            <input type=\"hidden\" name=\"page\" value=\"1\">\r\n");
          out.write("                            <input type = \"hidden\" name=\"clientId\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"/>\r\n");
          out.write("                            <input type = \"submit\" class=\"btn btn-primary\" value = '");
          if (_jspx_meth_lang_005fprint_005f7(_jspx_th_c_005fif_005f6, _jspx_page_context))
            return true;
          out.write("'/>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f7(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f7 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f7_reused = false;
    try {
      _jspx_th_lang_005fprint_005f7.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f7.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
      // /view/header.jsp(61,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f7.setMessage("header.jsp.my.orders");
      int _jspx_eval_lang_005fprint_005f7 = _jspx_th_lang_005fprint_005f7.doStartTag();
      if (_jspx_th_lang_005fprint_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f7);
      _jspx_th_lang_005fprint_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f7, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f8(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f8 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f8_reused = false;
    try {
      _jspx_th_lang_005fprint_005f8.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f8.setParent(null);
      // /view/header.jsp(66,80) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f8.setMessage("header.jsp.logout");
      int _jspx_eval_lang_005fprint_005f8 = _jspx_th_lang_005fprint_005f8.doStartTag();
      if (_jspx_th_lang_005fprint_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f8);
      _jspx_th_lang_005fprint_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f8, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /view/header.jsp(69,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <div class=\"icon\" style = \"text-align: center; width: 100px; \">\r\n");
          out.write("                            <img src=\"https://cdn-icons-png.flaticon.com/512/2206/2206200.png\" alt=\"user\" style = \"width: 60px; height: 60px; line-height: 60px; border-radius: 50%; font-size: 20px; background: #000\" />\r\n");
          out.write("                            <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.login}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f9(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f9 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f9_reused = false;
    try {
      _jspx_th_lang_005fprint_005f9.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f9.setParent(null);
      // /view/header.jsp(77,89) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f9.setMessage("common.message.update");
      int _jspx_eval_lang_005fprint_005f9 = _jspx_th_lang_005fprint_005f9.doStartTag();
      if (_jspx_th_lang_005fprint_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f9);
      _jspx_th_lang_005fprint_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f9, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /view/header.jsp(79,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("locale");
      // /view/header.jsp(79,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/header.jsp(79,28) '${sessionScope.locales}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.locales}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <option value = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                    ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                                </option>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f10(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f10 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f10_reused = false;
    try {
      _jspx_th_lang_005fprint_005f10.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f10.setParent(null);
      // /client/clientHome.jsp(11,12) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f10.setMessage("clientHome.jsp.hello");
      int _jspx_eval_lang_005fprint_005f10 = _jspx_th_lang_005fprint_005f10.doStartTag();
      if (_jspx_th_lang_005fprint_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f10);
      _jspx_th_lang_005fprint_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f10, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f11(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f11 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f11_reused = false;
    try {
      _jspx_th_lang_005fprint_005f11.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f11.setParent(null);
      // /client/clientHome.jsp(16,16) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f11.setMessage("clientHome.jsp.about.cargo.application");
      int _jspx_eval_lang_005fprint_005f11 = _jspx_th_lang_005fprint_005f11.doStartTag();
      if (_jspx_th_lang_005fprint_005f11.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f11);
      _jspx_th_lang_005fprint_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f11, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f12(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f12 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f12_reused = false;
    try {
      _jspx_th_lang_005fprint_005f12.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f12.setParent(null);
      // /client/clientHome.jsp(18,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f12.setMessage("clientHome.jsp.this.is.your.home.page");
      int _jspx_eval_lang_005fprint_005f12 = _jspx_th_lang_005fprint_005f12.doStartTag();
      if (_jspx_th_lang_005fprint_005f12.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f12);
      _jspx_th_lang_005fprint_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f12, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f13(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f13 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f13_reused = false;
    try {
      _jspx_th_lang_005fprint_005f13.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f13.setParent(null);
      // /client/clientHome.jsp(19,20) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f13.setMessage("clientHome.jsp.at.the.top.of.the.page");
      int _jspx_eval_lang_005fprint_005f13 = _jspx_th_lang_005fprint_005f13.doStartTag();
      if (_jspx_th_lang_005fprint_005f13.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f13);
      _jspx_th_lang_005fprint_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f13, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f14(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f14 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f14_reused = false;
    try {
      _jspx_th_lang_005fprint_005f14.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f14.setParent(null);
      // /client/clientHome.jsp(21,28) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f14.setMessage("clientHome.jsp.place.an.order.for.delivery");
      int _jspx_eval_lang_005fprint_005f14 = _jspx_th_lang_005fprint_005f14.doStartTag();
      if (_jspx_th_lang_005fprint_005f14.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f14);
      _jspx_th_lang_005fprint_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f14, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f15(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f15 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f15_reused = false;
    try {
      _jspx_th_lang_005fprint_005f15.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f15.setParent(null);
      // /client/clientHome.jsp(22,22) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f15.setMessage("clientHome.jsp.about.button.place.an.order.for.delivery");
      int _jspx_eval_lang_005fprint_005f15 = _jspx_th_lang_005fprint_005f15.doStartTag();
      if (_jspx_th_lang_005fprint_005f15.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f15);
      _jspx_th_lang_005fprint_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f15, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f16(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f16 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f16_reused = false;
    try {
      _jspx_th_lang_005fprint_005f16.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f16.setParent(null);
      // /client/clientHome.jsp(24,28) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f16.setMessage("clientHome.jsp.my.orders");
      int _jspx_eval_lang_005fprint_005f16 = _jspx_th_lang_005fprint_005f16.doStartTag();
      if (_jspx_th_lang_005fprint_005f16.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f16);
      _jspx_th_lang_005fprint_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f16, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f17(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f17 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f17_reused = false;
    try {
      _jspx_th_lang_005fprint_005f17.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f17.setParent(null);
      // /client/clientHome.jsp(25,22) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f17.setMessage("clientHome.jsp.clientHome.jsp.about.button.my.orders");
      int _jspx_eval_lang_005fprint_005f17 = _jspx_th_lang_005fprint_005f17.doStartTag();
      if (_jspx_th_lang_005fprint_005f17.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f17);
      _jspx_th_lang_005fprint_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f17, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f18(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f18 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f18_reused = false;
    try {
      _jspx_th_lang_005fprint_005f18.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f18.setParent(null);
      // /client/clientHome.jsp(27,28) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f18.setMessage("clientHome.jsp.my.wallet");
      int _jspx_eval_lang_005fprint_005f18 = _jspx_th_lang_005fprint_005f18.doStartTag();
      if (_jspx_th_lang_005fprint_005f18.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f18);
      _jspx_th_lang_005fprint_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f18, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f18_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f19(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f19 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f19_reused = false;
    try {
      _jspx_th_lang_005fprint_005f19.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f19.setParent(null);
      // /client/clientHome.jsp(28,22) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f19.setMessage("clientHome.jsp.about.button.my.wallet");
      int _jspx_eval_lang_005fprint_005f19 = _jspx_th_lang_005fprint_005f19.doStartTag();
      if (_jspx_th_lang_005fprint_005f19.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f19);
      _jspx_th_lang_005fprint_005f19_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f19, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f19_reused);
    }
    return false;
  }
}
