/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.14
 * Generated at: 2022-10-24 10:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.client;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class successRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("file:/C:/Users/Серёга/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1652529507264L));
    _jspx_dependants.put("jar:file:/C:/Users/Серёга/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602863172000L));
    _jspx_dependants.put("/WEB-INF/tag/language.tld", Long.valueOf(1666435784466L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Welcome page</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("        <h1>\r\n");
      out.write("            ");
      if (_jspx_meth_lang_005fprint_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </h1>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <form action = \"/app/cargo/login\" method = \"POST\">\r\n");
      out.write("            <label for=\"name\">");
      if (_jspx_meth_lang_005fprint_005f1(_jspx_page_context))
        return;
      out.write("</label><br>\r\n");
      out.write("            <input type=\"text\" name=\"login\" pattern=\".{3,}\" title='Three or more characters required' required ><br><br>\r\n");
      out.write("            <label for=\"pass\">");
      if (_jspx_meth_lang_005fprint_005f2(_jspx_page_context))
        return;
      out.write("</label><br>\r\n");
      out.write("            <input type=\"password\" name=\"password\" pattern=\"(?=.*\\d)(?=.*[a-zа-яії])(?=.*[A-ZА-ЯІЇ]).{8,}\" title='Must contain at least one  number and one uppercase and lowercase letter, and at least 8 or more characters' required><br><br>\r\n");
      out.write("            <input type = \"submit\" style=\"width: 8%\" class=\"btn btn-primary\" value='");
      if (_jspx_meth_lang_005fprint_005f3(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("        </form>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_lang_005fprint_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f0 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f0_reused = false;
    try {
      _jspx_th_lang_005fprint_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f0.setParent(null);
      // /client/successRegistration.jsp(11,12) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f0.setMessage("successRegistration.jsp.registration.successful.please.enter");
      int _jspx_eval_lang_005fprint_005f0 = _jspx_th_lang_005fprint_005f0.doStartTag();
      if (_jspx_th_lang_005fprint_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f0);
      _jspx_th_lang_005fprint_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f0, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f1 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f1_reused = false;
    try {
      _jspx_th_lang_005fprint_005f1.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f1.setParent(null);
      // /client/successRegistration.jsp(17,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f1.setMessage("index.jsp.login");
      int _jspx_eval_lang_005fprint_005f1 = _jspx_th_lang_005fprint_005f1.doStartTag();
      if (_jspx_th_lang_005fprint_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f1);
      _jspx_th_lang_005fprint_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f1, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f2 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f2_reused = false;
    try {
      _jspx_th_lang_005fprint_005f2.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f2.setParent(null);
      // /client/successRegistration.jsp(19,30) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f2.setMessage("index.jsp.password");
      int _jspx_eval_lang_005fprint_005f2 = _jspx_th_lang_005fprint_005f2.doStartTag();
      if (_jspx_th_lang_005fprint_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f2);
      _jspx_th_lang_005fprint_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f2, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lang_005fprint_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  lang:print
    cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport _jspx_th_lang_005fprint_005f3 = (cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport) _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.get(cargo.delivery.epam.com.project.infrastructure.web.tag.LanguageTagSupport.class);
    boolean _jspx_th_lang_005fprint_005f3_reused = false;
    try {
      _jspx_th_lang_005fprint_005f3.setPageContext(_jspx_page_context);
      _jspx_th_lang_005fprint_005f3.setParent(null);
      // /client/successRegistration.jsp(21,84) name = message type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lang_005fprint_005f3.setMessage("index.jsp.log.in");
      int _jspx_eval_lang_005fprint_005f3 = _jspx_th_lang_005fprint_005f3.doStartTag();
      if (_jspx_th_lang_005fprint_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flang_005fprint_0026_005fmessage_005fnobody.reuse(_jspx_th_lang_005fprint_005f3);
      _jspx_th_lang_005fprint_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lang_005fprint_005f3, _jsp_getInstanceManager(), _jspx_th_lang_005fprint_005f3_reused);
    }
    return false;
  }
}
